### ISSUE TITLE
The relation between impressions and interactions

### ISSUE THREAD

**Issue by ryaninhust** [recsyschallenge/2016#11]
Hi organizers , @fabianabel 
May I ask the relation between impressions  and interactions, whether these interactions came from impressions, or just collected from global site? Many thanks

**Comment by dkohlsdorf** [comment]
Hello, 
impressions are items or jobs shown to the user by the system. For example, jobs recommended to the user by our recommendations.
Interactions are items the user clicked, bookmarked, replied to a job posting or deleted it. In other words, 
there are three types of positive interactions and one negative

Hope that helps and happy hacking,
Daniel

**Comment by ryaninhust** [comment]
@dkohlsdorf 
Thanks, as you said, impressions came from the recommender. but how about these interactions?
that is to say, `interactions.csv` includes and only includes the ones which users created after they saw impressions from the recommender. right?

**Comment by dkohlsdorf** [comment]
Where does it say that? The interactions can happen without a recommender showing it. A user can 
get to a job posting without an impression (for example through search)

**Comment by ryaninhust** [comment]
@dkohlsdorf  Got it, thanks,
BTW,  how will the ground truth rank the items' relevance to each user?
Is there any explicit order for the three types of positive?

**Comment by dkohlsdorf** [comment]
Nope all positively interacts count the same and we do not count deletes

Daniel
