### ISSUE TITLE
edu_degree values not conforming to description

### ISSUE THREAD

**Issue by Lifeindeath** [recsyschallenge/2016#12]
The description says that edu_degree values range from 0 to 3, but analyzing the dataset we found that the actual range is 0-6. Is it an error in the description? What's the actual meaning of those values?

**Comment by creat89** [comment]
I extracted the 11th column from the users.csv and I didn't find values higher than 3, at least for the 1,367,057 unique users.

Here are the results:

'0' => 835586,
'2' => 318248,
'1' => 159232,
'3' => 53696,
'NULL' => 295

BTW, I'm not an organizer.

**Comment by Lifeindeath** [comment]
too bad, I may have messed with the datasets!
