### ISSUE TITLE
about "creat_at"

### ISSUE THREAD

**Issue by zhengrongqin** [recsyschallenge/2016#18]
how long does the "creat_at" contained in the interactions.csv file represent?  a year?

**Comment by dkohlsdorf** [comment]
No, not a year. The interactions are in range:
- Wed, 19 Aug 2015 
- Sun, 08 Nov 2015 
  by the way, all the timestamps are unix timestamps so you can convert them
  to a date. For example, http://www.onlineconversion.com/unix_time.htm
  or in your shell

Daniel

**Comment by zhengrongqin** [comment]
@dkohlsdorf    OK ， thank you  again
