### ISSUE TITLE
Question about rounding and click sequence in dataset

### ISSUE THREAD

**Issue by btwardow** [recsyschallenge/2016#2]
Hi, 

in dataset description of the interactions we can read:

> timestamp (Unix timestamp, rounded to 5 min)

Are You planing to do this rounding in a way that we will be able to get an actual click sequence in a session? I think it is important information information. 

Regards, 
B.Twardowski

**Comment by fabianabel** [comment]
In the current version, the timestamp will not allow for extracting the click sequence, but the order in the CSV files that we will release does. 

We keep an eye on that issue and will then explicitly write a comment about "sequence of clicks" in the description of the dataset.

**Comment by fabianabel** [comment]
In the released dataset, the timestamps allow for inferring the actual click sequence.

**Comment by btwardow** [comment]
Ok. Thank You @fabianabel .
