### ISSUE TITLE
How to measure the relevance between user and item in the next week?

### ISSUE THREAD

**Issue by Cherishzhang** [recsyschallenge/2016#22]
Relevant items are those items on which a user clicked, bookmarked or replied (interaction_type= 1, 2 or 3). 

I want to build a local evaluation, But I has a question, how to measure it? Just by the value of the interaction_type, or related to the interaction create time, or related to the times the item interacted by the user.

**Comment by dkohlsdorf** [comment]
You could slice the data by date and then try to predict the clicked items in that time.
The formulas are given to you at: https://github.com/recsyschallenge/2016/blob/master/EvaluationMeasure.md

Daniel

**Comment by Cherishzhang** [comment]
@dkohlsdorf , thanks for your reply!
