### ISSUE TITLE
question on Metric : Precision at k. What if len(recommendation) < k

### ISSUE THREAD

**Issue by skywaLKer518** [recsyschallenge/2016#23]
In the document, the pseudocode returns 

topK = recommendedItems.take(k)
return intersect(topK, relevantItems).size / **k**

My question is, what if L = len(recommendedItems) < k?
Does the metric return  intersect(topK, relevantItems).size / **min(k, L)**?

In other words, does the evaluation encourage submitting less items but accurate or more that seeking good recall?

Thanks!

Kuan

**Comment by fabianabel** [comment]
Hi Kuan, 

thank you for asking! If `recommendedItems.size < k` then we still divide by `k` (for good reasons :-) 

Thanks,
fabian
