### ISSUE TITLE
Question on the order of the test set

### ISSUE THREAD

**Issue by liangkang** [recsyschallenge/2016#24]
Since the score is related to the order of items in the test set, can we know the rule of the order? If we don't know that, I think the offline evaluation is ugly. THX.

**Comment by fabianabel** [comment]
The order of the "relevant items" does not matter. For example (see [EvaluationMeasure.md](https://github.com/recsyschallenge/2016/blob/master/EvaluationMeasure.md)):

``` javascript
...
function precisionAtK(recommendedItems, relevantItem, k) = {
  topK = recommendedItems.take(k) //takes first k items from the list of reccommendedItems
  return intersect(topK, relevantItems).size / k
}
...
```

Here, `relevantItems` can be considered as an unordered set. 

Cheers,
fabian
