### ISSUE TITLE
Invalid user_ids

### ISSUE THREAD

**Issue by yoonholee** [recsyschallenge/2016#25]
There are user_ids in impressions that don't appear in users.

For example, the first user_id in impressions is 1842650, which isn't a string that is not in users.
Is this intentional? According to a script I wrote, around 33% of user_ids in impressions are invalid.

**Comment by dkohlsdorf** [comment]
Hey, sorry that error has to do with a previous error during the exporting. Please just ignore these users.

Sorry again,
Daniel
