### ISSUE TITLE
Deadline for submitting solutions

### ISSUE THREAD

**Issue by B4S3** [recsyschallenge/2016#27]
What is the exact date for submitting solutions?

**Comment by B4S3** [comment]
Hello again my friends!

Is this competition permanently dead? When the final submission deadline will be anounced?

**Comment by B4S3** [comment]
Hello again my friends!

Is this competition permanently dead? When the final submission deadline will be anounced?

**Comment by B4S3** [comment]
Hello again my friends!

Is this competition permanently dead? When the final submission deadline will be anounced?

**Comment by dkohlsdorf** [comment]
The deadline will be announced soon. It will be somewhen in end of June.

Daniel

**Comment by B4S3** [comment]
This "end of June" sounds very similar to "end of December" when competition was about to begin.

![a](https://cloud.githubusercontent.com/assets/13643001/15023026/d0fe4e6e-122e-11e6-886f-3184fc902fbe.png)

**Comment by tommycarpi** [comment]
How much time will we have then to write and submit the paper??

**Comment by rpalovics** [comment]
We intend to give you at least 3 weeks [hopefully 4]  to submit your paper. We are just about to announce the final deadlines. Thank you for your patience.

**Comment by Lifeindeath** [comment]
And when will the teams invited to the conference be announced? I think that everybody will need time to organize the trip :) ...

**Comment by fabianabel** [comment]
The deadline for submitting solutions is June 26th (23:59 Hawaiian time) - now also on http://2016.recsyschallenge.com/ 

Other remarks: 
- paper deadlines will follow soon (most likely, the paper submission deadline will be mid of July and the notification deadline will be mid of August)
- @tommycarpi  in case you would like to start writing already your paper now, then I suggest to use the same template as for the main conference (https://recsys.acm.org/recsys16/submission/). 
- @Lifeindeath teams can plan their trip to the RecSys conference and RecSys workshop independently from paper the paper submissions if you like (e.g. you can join the RecSys workshop also without presenting a paper)

**Comment by Merlin55** [comment]
In users.csv, and items.csv ,the 'title', 'tags' are a list of Numberic IDs.Can you make it clear that,the range of Numberic IDs?

**Comment by fabianabel** [comment]
Those IDs are positive integers. Each ID represents a certain concept. For example, there may be an ID such as 42 that corresponds to a concept that has labels such as "Data Scientist", "Data Mining Expert". The meaning of the IDs is "stable", i.e. ID 42 always has the same meaning (no matter whether it appears in the posting's title or in the user's skills.
