### ISSUE TITLE
About the rule "Your algorithm should not attempt to identify artificial users, or reconstruct flipped values."

### ISSUE THREAD

**Issue by Neurodis** [recsyschallenge/2016#33]
I would like to learn some details about this rule. As we do accept not to try to reconstruct your flipped data, we would like to make some assumptions and change some of the unknown values. Would this be a violation of rules or just like a different default values for different users ?  

ex: (Lets say the experience in years value is 5, but the careerlevel is null. I would like to assume the careerlevel as 3 or 4) 

Thanks

**Comment by fabianabel** [comment]
Trying to infer values for such default values is perfectly fine! It is also perfectly fine if you would try to model the users/items in some other (vector) space if this helps your algorithm. Trying to identify users (e.g. trying to connect the ID of a user with the name of a person) is forbidden. 
Cheers,
fabian
