### ISSUE TITLE
We have created a team

### ISSUE THREAD

**Issue by CineCoin** [recsyschallenge/2016#34]
Excuse me, we have created a team named "Cine".
Hope it could be  approved if convenient.

**Comment by fabianabel** [comment]
Done.

**Comment by CineCoin** [comment]
Thank you very much!~
By the way, the submission system seems not working right now.

**Comment by fabianabel** [comment]
I just tried to submit a solution and things work smoothly for me.

**Comment by CineCoin** [comment]
yes it gets right this time. thx.
