### ISSUE TITLE
Could we get one of the previous results submitted?

### ISSUE THREAD

**Issue by CineCoin** [recsyschallenge/2016#35]
Hi friends, we have submitted several results till now.
But unfortunately we covered some results by mistake, including which got the best score ever. It takes too much time to run a new result to make improvement on it.
Are there any method to get the previous results submitted from your server?
Our team is "Cine" and the label of result we want to get is "lda cosine similarity".
Thanks all the same if it's impossible.

**Comment by fabianabel** [comment]
Dear Cine Team, 

I sent you (= the leader of your team) a message via XING with the CSV file of your submission attached. 

Cheers,
fabian

**Comment by CineCoin** [comment]
THX:)
