### ISSUE TITLE
something about submission time

### ISSUE THREAD

**Issue by CineCoin** [recsyschallenge/2016#36]
Hi friend, we submitted a result at 23:50(Hawaii time), while the result(score) showed off at 00:01, which could be found in the submission records.
Unfortunately, this leads to our result showing in the unofficial leaderboard rather than the official one.
We wonder would this result be considered in the official leaderboard?
Looking forward to your reply and thank you very much.
Team "Cine" again and the submission label is "final1".

**Comment by fabianabel** [comment]
Thank you for your enthusiasm! Sorry, we received the submission at 12:01:02 and that's the time that counts. I can thus not include it into the official leaderboard.
