### ISSUE TITLE
Issue about participating the workshop

### ISSUE THREAD

**Issue by mogami95** [recsyschallenge/2016#38]
Dear organizer:
    Our team will be eager and sure to participate this workshop in Boston if our accompanied paper is accepted.
So, there is a request that will you issue (send) us a (more) formal invitation letter if our accompanied paper is accepted? To be honest, it is really hard to apply the VISA only by right of the letter you sent on July 14th.
    And our very last question is how many participants are allowed to register the workshop in one single team?  Could all of the authors participate this workshop in September?

Thanks.

**Comment by fabianabel** [comment]
As a participant of the challenge, you can register for the workshop also without having an accepted paper. Hence, you could already sign up now. 

Feel free to register for the workshop with your entire team. As far as I understood, the room that we will get for our workshop fill offer space for around 30 participants.

**Comment by mogami95** [comment]
First, thanks for your patient answering. I have seen the registration procedure on the main page of RecSys 2016 and find that all registration items need fee payments. I still wanna know if there is free registration fee after our paper accepted. 
I am looking forward to your straightforward reply. Thank you.
