### ISSUE TITLE
Regarding Dataset 

### ISSUE THREAD

**Issue by maneeshv11** [recsyschallenge/2016#4]
When will the data-set be available ??

**Comment by dkohlsdorf** [comment]
We are working on it. We plan to release beginning of next week.

**Comment by skallumadi** [comment]
Hi, Any updates? thanks!

**Comment by shrev** [comment]
Hi, can you give us an exact date as to when the datasets will be released?

**Comment by fabianabel** [comment]
The dataset is now available via the [submission system](https://recsys.xing.com/).
