### ISSUE TITLE
Workshop proceedings

### ISSUE THREAD

**Issue by fabianabel** [recsyschallenge/2016#40]
We will post the link to the proceedings here and close this issue as soon as the workshop proceedings are published by ACM.

**Comment by B4S3** [comment]
How about this?
http://dl.acm.org/citation.cfm?id=2987538&picked=prox&cfid=706129956&cftoken=30882812

**Comment by fabianabel** [comment]
Great, thank you for posting the link! I added it also to the [website](http://2016.recsyschallenge.com/).
