### ISSUE TITLE
Problem about the  rule & submission

### ISSUE THREAD

**Issue by mogami95** [recsyschallenge/2016#6]
Hi, we found a conflict on the page https://recsys.xing.com/rules , it says "the submission limits: you can upload at maximum 5 solutions per day"
And on the top of the submission page https://recsys.xing.com/submission , it also says "New Submission    5 submissions still possible for you today", however on the bottom of this page https://recsys.xing.com/submission , shows that "Additional remarks:  No.4  Notice that you can only submit 3 solutions per calendar day".

So, how many solutions can i submit  per calendar day actually?
And which Time Zone is the standard? GMT or another?

**Comment by mogami95** [comment]
Note that i have not uploaded any solution yet till now

**Comment by dkohlsdorf** [comment]
You should be able to submit 5 submissions a day

Daniel

On Mon, Feb 29, 2016 at 11:50 AM, MiaoLoud notifications@github.com wrote:

> Note that i have not uploaded any solution yet till now
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/recsyschallenge/2016/issues/6#issuecomment-190152040.

## 

Daniel Kyu Hwa KohlsdorfMAIL: dkohlsdorf [at] googlemail.com _WEB_:
dkohl.org

**Comment by fabianabel** [comment]
Thank you for spotting this. It is now corrected to _5 submissions_ on https://recsys.xing.com/submission

**Comment by fabianabel** [comment]
And we take Hamburg's timezone (_UTC+01:00_) as time zone to decide on the calendar day.
