### ISSUE TITLE
How many teams that participate in the challenge can be allowed to attend the workshop?

### ISSUE THREAD

**Issue by lvfuyu** [recsyschallenge/2016#7]
rt

**Comment by mogami95** [comment]
rt is the chinese abbreviation, i think the original poster want to deliver "as the title says"...

**Comment by liangkang** [comment]
yes, you are right

**Comment by liangkang** [comment]
and I just wanna know, when the workshop starts

**Comment by fabianabel** [comment]
We are aiming for a workshop with around 30 participants at RecSys in Boston. The format of the workshop (e.g. full/half-day, types of presentations, etc.) will depend on the number and quality of submissions that we will receive. The workshop will take place on September 15th or 16th. 

Regarding paper submissions/presentations: any participant of the challenge can submit a workshop paper. The three top-teams, who achieved the highest scores, will be prioritized. More details will follow as soon as we know more about the number/quality of solutions. So for now: enjoy the challenge! 

Thank you for clarifying `rt` :-)
