### ISSUE TITLE
Can you tell me that the meaning of the items order & repetition in "Impressions.csv"?

### ISSUE THREAD

**Issue by mogami95** [recsyschallenge/2016#9]
Many records in "Impressions.csv" show as following: 
user_id year    week    items
1842650 2015    41  1386585,1386585,2139076,766293,977414,1133414,1163212
## ..............  ........        ...      ............................

Could you tell me that the meaning of the item order & repetition in "Impressions.csv"?
(If the rules allow it)
thank you ^o^

**Comment by mogami95** [comment]
And i also want to know if you shifted all timestamps in "Impressions.csv" (year-week) &  "interactions.csv" (unix timestamp) with the same way? Are the timestamps in these 2 files still consistent?

**Comment by dkohlsdorf** [comment]
Yes they are shifted in the same way. Also there is no ordere assumed in the impressions for a given row

**Comment by douglashiwo** [comment]
how about the meaning of repetition？ I mean for some impression ，posting ID like 1386585 can repeat several times and more ，can we treat it as the number of times that the previous RS had recommended for a single item(posting？) 
Looking forward to your reply!  thank you

**Comment by BrightFeather** [comment]
How should we use this data? I mean, is the impression a benchmark for examining the correctness of our result?

**Comment by dkohlsdorf** [comment]
Well a job can be recommended multiple times to a user. One example of what you can do with an impression is to distinguish between things shown by the recommender or searched by the user directly. However, we don't say you have to use the impression. 

Daniel

**Comment by mogami95** [comment]
@dkohlsdorf  Thanks for your explanation. And my last question is: Whether the "impression"  was the results of your baseline algorithm(https://github.com/recsyschallenge/2016/blob/master/Baselines.md), or not?

**Comment by dkohlsdorf** [comment]
Nope the baseline is not related to the algorithm run on the platform. The algorithm on the platform has way more components and filters. So relating the baseline algorithm to the impressions might not be advisable.
